### ISSUE TITLE
AttributeError: module 'albumentations' has no attribute 'Sequentials'

### ISSUE THREAD

**Issue by schleptech** [alexppppp/keypoint_rcnn_training_pytorch#2]
I ran your notebook exactly as it showed in Google Colab and am getting the following error.... can you help?

**Comment by alexppppp** [comment]
You need to install a newer version of albumentations library

**Comment by schleptech** [comment]
I read that Google colab has an outdated version, so I ran the following at the beginning of the notebook:

`!pip install -q -U albumentations`
`!echo "$(pip freeze | grep albumentations) is successfully installed"`

[https://colab.research.google.com/github/albumentations-team/albumentations_examples/blob/colab/tensorflow-example.ipynb#scrollTo=26f58a5d]

However, when I get to that step again, I am still getting the error

`AttributeError: module 'albumentations' has no attribute 'Sequential'`

**Comment by alexppppp** [comment]
So, the error disappeared, correct?

P.S. This way of update is preferrable (from https://albumentations.ai/docs/getting_started/installation/):
_If you already have some OpenCV distribution (such as opencv-python-headless, opencv-python, opencv-contrib-python or opencv-contrib-python-headless) installed in your Python environment, you can force Albumentations to use it by providing the --no-binary qudida,albumentations argument to pip, e.g._
**pip install -U albumentations --no-binary qudida,albumentations**

**Comment by schleptech** [comment]
Yes - updated my notebook to reflect your above suggestion.

Now when I get down to step 4, "4. Visualizing a random item from dataset", I get the following error:

`SystemError: new style getargs format but argument is not a tuple`

Seems to be an opencv error

Full output:
SystemError                               Traceback (most recent call last)
[<ipython-input-19-4d347bcf7114>](https://localhost:8080/#) in <module>()
     51     keypoints_original.append([kp[:2] for kp in kps])
     52 
---> 53 visualize(image, bboxes, keypoints, image_original, bboxes_original, keypoints_original)

[<ipython-input-19-4d347bcf7114>](https://localhost:8080/#) in visualize(image, bboxes, keypoints, image_original, bboxes_original, keypoints_original)
     27             for idx, kp in enumerate(kps):
     28                 image_original = cv2.circle(image_original, tuple(kp), 5, (255,0,0), 10)
---> 29                 image_original = cv2.putText(image_original, " " + keypoints_classes_ids2names[idx], (kp), cv2.FONT_HERSHEY_SIMPLEX, 2, (255,0,0), 3, cv2.LINE_AA)
     30 
     31         f, ax = plt.subplots(1, 2, figsize=(40, 20))

`

**Comment by alexppppp** [comment]
Yes, the same for me

It can be fixed with changing this line:
**image_original = cv2.putText(image_original, " " + keypoints_classes_ids2names[idx], (kp), cv2.FONT_HERSHEY_SIMPLEX, 2, (255,0,0), 3, cv2.LINE_AA)**

to this line:
**image_original = cv2.putText(image_original, " " + keypoints_classes_ids2names[idx], tuple(kp), cv2.FONT_HERSHEY_SIMPLEX, 2, (255,0,0), 3, cv2.LINE_AA)**

**Comment by schleptech** [comment]
Good deal! Got everything to work for me - 
so to summarize - I followed your step of
`pip install -U albumentations --no-binary qudida,albumentations`

Which installed the newer version of albumentations (colab has an old version) and the script also brought in the appropriate  opencv-python-headless.
Note: in google colab (which I am not familiar with particularly; I primarily use AWS EC2 instances via SSH) you must restart the runtime!

Also remember to change cocoeval.py everytime you bring the runtime back up.

Working just as you specified. Thanks!
