### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by Arunpoochelvan** [alexppppp/keypoint_rcnn_training_pytorch#8]
ValueError: operands could not be broadcast together with shapes (2,) (17,)

**Comment by bujiebuhuo** [comment]
Did you solve your problem, I have the same problem.

**Comment by Arunpoochelvan** [comment]
yes I solved try this

i did this in coco_eval.py(line 22), so i change the kpt_oks_sigmas after instantiating :

for iou_type in iou_types:
# self.coco_eval[iou_type] = COCOeval(coco_gt, iouType=iou_type)
coco_eval = COCOeval(coco_gt, iouType=iou_type)
coco_eval.params.kpt_oks_sigmas = np.array([.5, .5]) / 10.0
self.coco_eval[iou_type] = coco_eval

after restart the runtime and try again it works

**Comment by alexppppp** [comment]
Hi @Arunpoochelvan @bujiebuhuo 

Please check this original article, which describes the whole script step by step:
https://medium.com/@alexppppp/how-to-train-a-custom-keypoint-detection-model-with-pytorch-d9af90e111da

I've described how to solve **(2,) (17,)** problem in the begining of the article

**Comment by bujiebuhuo** [comment]
> 

This blog can solve my problem, thank you.
